[workspace]
members = [
  "futuremod_engine",
  "futuremod",
  "futuremod_data",
  "futuremod_hook",
]
resolver = "2"

[profile.release.package.futuremod_hook]
opt-level = 0  # Completely disable optimizations for dll due to issues with raw memory modification