[workspace]
members = [
  "futurecop_mod",
  "futurecop_injector",
  "futurecop_data",
]
resolver = "2"

[profile.release.package.futurecop-mod]
opt-level = 0  # Completely disable optimizations for dll due to issues with raw memory modification