[package]
name = "futurecop_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
serde = {version = "1.0.197", feature = ["serde_derive"]}
serde_derive = "1.0.197"
