name: Release

on:
  release:
    types: [published]


jobs:
  debug_release:
    name: Release a Debug Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: Build
        run: cargo build
      - name: Package files
        run: |
          cd ./target/i686-pc-windows-msvc/debug
          zip futuremod-debug.zip futurecop_mod.dll futurecop_mod.pdb futuremod.exe
      - name: Upload packaged debug release
        run: gh release upload ${{ github.ref }} futuremod-debug.zip
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: Build
        run: cargo build --release
      - name: Package files
        run: |
          cd ./target/i686-pc-windows-msvc/release
          zip futuremod.zip futurecop_mod.dll futurecop_mod.pdb futuremod.exe
      - name: Upload debug build
        run: gh release upload ${{ github.ref }} futuremod.zip
