name: Release

on:
  release:
    types: [published]


jobs:
  debug_release:
    name: Release a Debug Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install necessary Windows target
        run: rustup target add i686-pc-windows-msvc
      - name: Build
        run: cargo build
      - name: Package files
        uses: vimtor/action-zip@v1.2
        with:
          files: target/i686-pc-windows-msvc/debug/futurecop_mod.dll target/i686-pc-windows-msvc/debug/futurecop_mod.pdb target/i686-pc-windows-msvc/debug/futuremod.exe
          dest: futuremod-debug.zip
      - name: Upload packaged debug release
        run: gh release upload ${{ github.ref }} futuremod-debug.zip
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install necessary Windows target
        run: rustup target add i686-pc-windows-msvc
      - name: Build
        run: cargo build --release
      - name: Package files
        uses: vimtor/action-zip@v1.2
        with:
          files: target/i686-pc-windows-msvc/release/futurecop_mod.dll target/i686-pc-windows-msvc/release/futuremod.exe
          dest: futuremod.zip
      - name: Upload release build
        run: gh release upload ${{ github.ref }} futuremod.zip
